repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: bash -c 'source .venv/bin/activate && mypy src'
        language: system
        pass_filenames: false
    -   id: pytest
        name: pytest
        entry: bash -c 'source .venv/bin/activate && pytest'
        language: system
        pass_filenames: false
        always_run: true
